language: python
python:
  - "3.5"

cache: pip3

install:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
    - coverage run -m unittest
    - coverage report
    
after_success:
    - coveralls
